### ISSUE TITLE
点击文章内部链接出错

### ISSUE THREAD

**Issue by xxred** [FourLeafClover/CNBlogApp#1]
![image](https://user-images.githubusercontent.com/19650464/45344662-e7b7a080-b5d6-11e8-9432-ae00932adfda.png)
![image](https://user-images.githubusercontent.com/19650464/45344821-382efe00-b5d7-11e8-92ed-48117feaa0dd.png)
![image](https://user-images.githubusercontent.com/19650464/45344832-3f560c00-b5d7-11e8-918b-483c33a5a3dd.png)
博客原文已改，大佬可以自己再重现下
原因是打开文件异常吧，这个链接被当成文件处理，而应用没有处理打开文件异常导致应用崩溃

**Comment by Frank-C-Zhang** [comment]
@xxred  我看了一哈, a标签配置 https://github.com/anjoy8/Blog.Vue是OK的 。但是配置的如果只是 //github.com/anjoy8/Blog.Vue 就不行了，cordova应该做了处理的。就当做本地路径了。而web站点是可以解析的。不知道楼主配置的a标签是否带了https

**Comment by xxred** [comment]
实际情况是https://github.com/anjoy8/Blog.Vue前面多了两个空格，程序当成文件解析而不是打开链接。读取不存在的文件报异常，这个处理好就行了

**Comment by Frank-C-Zhang** [comment]
@xxred  OK。那我先关闭issue了。我就不在页面对面所有a标签做去空格判断处理了。
